Repository swizzin/swizzin, pull requests merged in 2021-08, with the labels that each got.

#731 fix: kill chpasswd if user does not exist
  scripts/box
Labels: bug, ez quick merge

#729 feat: add bullseye support
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  scripts/box
  setup.sh
  sources/functions/deluge
  sources/functions/mono
Labels: enhancement

#734 feat: Autobrr
  scripts/box
  scripts/install/autobrr.sh
  scripts/nginx/autobrr.sh
  scripts/remove/autobrr.sh
  scripts/tests/autobrr.sh
  scripts/upgrade/autobrr.sh
  sources/functions/autobrr
  sources/lang_en
Labels: New App PR, ez quick merge

#752 hotfix(autodl): use gui-server-port and gui-server-password
  scripts/install/rutorrent.sh
  scripts/nginx/autodl.sh
Labels: bug, ez quick merge

#693 feat(box): stay on develop over `box update` runs, allow auto-testing
  .gitignore
  scripts/box
Labels: enhancement
