Repository swizzin/swizzin, pull requests merged in 2021-11, with the labels that each got.

#764 Feat: Mylar
  scripts/install/mylar.sh
  scripts/nginx/mylar.sh
  scripts/remove/mylar.sh
  scripts/tests/mylar.sh
  scripts/upgrade/mylar.sh
  sources/lang_en
Labels: New App PR, ez quick merge

#784 Feat: Navidrome
  scripts/install/navidrome.sh
  scripts/nginx/navidrome.sh
  scripts/remove/navidrome.sh
  scripts/tests/navidrome.sh
  scripts/upgrade/navidrome.sh
  sources/functions/navidrome
  sources/lang_en
Labels: New App PR, has conflicts

#798 Feat debug
  scripts/update/10-dependencies.sh
  scripts/update/debug.sh
  sources/functions/debug
Labels: Functions, ez quick merge
