Repository swizzin/swizzin, pull requests merged in 2021-01, with the labels that each got.

#573 IMPROVE: Nginx WebSocket support for Mango
  scripts/nginx/mango.sh
  scripts/update/mango.sh
Labels: enhancement

#577 SNIPPETS: Added nginx conf, and environment variable checks
  .vscode/general.code-snippets
Labels: enhancement

#548 Simplified, unattended setup
  CONTRIBUTING.md
  README.md
  scripts/box
  scripts/deluge.UpdateTracker.py
  scripts/install/duckdns.sh
  scripts/install/letsencrypt.sh
  scripts/install/subsonic.sh
  scripts/install/transmission.sh
  scripts/install/webmin.sh
  scripts/nginx/sonarrv3.sh
  scripts/nginx/transmission.sh
  scripts/nukeovh
  scripts/remove/libtorrent.sh
  scripts/remove/vsftpd.sh
  scripts/rtx
  scripts/update/10-dependencies.sh
  scripts/update/jellyfin.sh
  scripts/update/mango.sh
  scripts/update/organizr.sh
  scripts/update/radarr.sh
  scripts/update/sickchill.sh
  scripts/update/vsftpd.sh
  scripts/upgrade/filebrowser.sh
  scripts/upgrade/lounge.sh
  scripts/upgrade/nzbhydra.sh
  scripts/upgrade/sonarr.sh
  setup.sh
  sources/functions/apt
  sources/functions/backports
  sources/functions/transmission
  sources/functions/users
  sources/globals.sh
  unattend.example.env
Labels: DANGER, Functions

#580 Unattend refinements
  .gitattributes
  scripts/box
  scripts/update/sudoers.sh
  setup.sh
  sources/functions/transmission
  sources/functions/users
  unattend.example.env
Labels: bug, security
