Repository swizzin/swizzin, pull requests merged in 2021-05, with the labels that each got.

#656 feat(Komga): Add Komga
  scripts/install/komga.sh
  scripts/nginx/komga.sh
  scripts/remove/komga.sh
  scripts/upgrade/komga.sh
  sources/functions/java
Labels: New App PR

#661 feat(ombi): Switch sources to new repo, make v4 default
  scripts/install/ombi.sh
  scripts/update/ombi.sh
  scripts/upgrade/ombi.sh
Labels: bug

#655 fix(swizdb): handle bad keys in gets better
  sources/functions/swizdb
Labels: bug

#611 fix: broken sudoers with hyphens
  scripts/box
  scripts/update/sudoers.sh
Labels: bug

#651 fix(radarr): Updater echoes
  scripts/install/radarr.sh
  scripts/update/radarr.sh
Labels: bug

#673 fix(swizdb): ensure key dirs get returned in path calls
  sources/functions/swizdb
Labels: bug

#670 fix(rutorrent): Ensure /srv is created, get rid of cds, remove cloudscraper and python dep
  scripts/install/nginx.sh
  scripts/install/rutorrent.sh
  scripts/nginx/rutorrent.sh
  scripts/update/rutorrent.sh
Labels: bug, enhancement

#343 feat(lidarr): Moving to /opt/ and netcore switch
  scripts/install/lidarr.sh
  scripts/nginx/lidarr.sh
  scripts/remove/lidarr.sh
  scripts/update/lidarr.sh
  scripts/update/mono.sh
Labels: bug, enhancement

#674 feat: Prowlarr addition
  scripts/install/prowlarr.sh
  scripts/nginx/prowlarr.sh
  scripts/remove/prowlarr.sh
Labels: New App PR
