Repository swizzin/swizzin, pull requests merged in 2022-02, with the labels that each got.

#579 feat(flood): Jesec migration
  scripts/box
  scripts/install/flood.sh
  scripts/nginx/flood.sh
  scripts/remove/flood.sh
  scripts/update/flood.sh
  scripts/upgrade/flood.sh
Labels: enhancement, feedback requested, New App PR, needs a testin

#836 hotfix(sabnzbd): bump pyenv version
  scripts/install/sabnzbd.sh
  scripts/upgrade/sabnzbd.sh
Labels: bug, ez quick merge

#842 hotfix(sabnzbd): passively set variable
  scripts/upgrade/sabnzbd.sh
Labels: bug
